name: flake8
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-nb
    - name: Analysing python code with flake8
      run: |
        flake8 --count --max-line-length 140
    - name: Analysing jupyter notebook code with flake8-nb
      run: |
        flake8_nb --count --filename '*.ipynb' --ignore E121,E501,F821,E402 

